import type { Deal } from '../types/deal';

/**
 * Per-deal documents tab. Renders downloadable artifacts attached to
 * the deal, currently just the term-sheet PDF generated by
 * backend/scripts/generate-deal-pdfs.ts and hosted in Supabase Storage.
 *
 * Empty state
 * -----------
 * If pdfUrl is null (e.g. the script hasn't been run for a new deal
 * yet) we render a calm "No documents yet" card rather than a broken
 * download link.
 *
 * The link opens in a new tab so the PDF doesn't replace the SPA in
 * the user's browser history.
 */
export function DealDocuments({ deal }: { deal: Deal }) {
  if (!deal.pdfUrl) {
    return (
      <div className="bg-card border border-border-light rounded-lg p-8 text-center text-sm text-text-secondary">
        No documents available for this deal yet.
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <section className="bg-card border border-border-light rounded-lg p-5">
        <h2 className="text-base font-medium text-brand-dark mb-1">Documents</h2>
        <p className="text-[11px] text-text-tertiary mb-4">
          Stored in Supabase Storage. Public read; service-role write only.
        </p>

        <a
          href={deal.pdfUrl}
          target="_blank"
          rel="noopener noreferrer"
          className="flex items-center gap-4 bg-page border border-border-light rounded-md p-4 hover:border-brand-accent transition group"
        >
          <PdfIcon />
          <div className="flex-1 min-w-0">
            <div className="font-medium text-text-primary text-sm group-hover:text-brand-dark">
              {deal.name} — Term-sheet factsheet
            </div>
            <div className="text-[11px] text-text-secondary mt-0.5">
              PDF · Key economics, sponsor, sentiment signals, risk profile
            </div>
          </div>
          <span className="text-[11px] uppercase tracking-wide text-brand-accent font-medium shrink-0">
            Download ↗
          </span>
        </a>

        <p className="text-[10px] text-text-tertiary mt-3 leading-snug">
          Generated by{' '}
          <code className="text-brand-accent">backend/scripts/generate-deal-pdfs.ts</code> via
          Puppeteer (HTML → PDF) and uploaded to the{' '}
          <code className="text-brand-accent">deal-documents</code> Supabase Storage bucket.
        </p>
      </section>
    </div>
  );
}

function PdfIcon() {
  return (
    <span
      className="w-10 h-10 rounded bg-brand-dark text-page flex items-center justify-center text-[10px] font-mono font-bold shrink-0"
      aria-hidden
    >
      PDF
    </span>
  );
}
